#%RAML 1.0 DataType

#This file is located at dataTypes/address.raml

type: object
properties:
  FirstName?: string
  LastName?: string
  EmailAddress?: string
  BirthDate?:
    type: datetime
    example: 2016-03-24T14:00:00.000Z
    required: false
  HomePhone?: string
  PrimaryAddress?: address
  MobilePhone?: string
  SecondaryAddress?: address
  OtherPhone?: string
  Title?: string
  Nickname?: string
  MaidenName?: string
  PhotoOptIn?: string
  TextOptIn ?: string
  PhoneOptIn?: string
  EmailOptIn?: string
  HomeEmail?: string
  WorkEmail?: string
  OtherEmail?: string
  PreferredEmail?: string
  Race?: string
  Ethnicity?: string
  Gender?: string
  Marital Statu?: string
  University?: string
  Grade?: string

