#%RAML 1.0 DataType

#This file is located at dataTypes/ErrorResponse-data-type.raml

type: object
properties:
  interfacecode: string 
  creationdate: string
  errordescription: string
  errortype: string
  errorcause: string
  errormessage: string
