#%RAML 1.0 DataType

#This file is located at dataTypes/OrgRequest.raml

type: object
properties:
  id: string 
  organizationAccountName?: string | nil
  organizationPhone?: string | nil
  isOrganizationActive?: string 
  organizationBillingStreet?: string | nil
  organizationBillingCity?: string | nil
  organizationBillingState?: string | nil
  organizationBillingPostalCode?: string | nil
  organizationCountry?: string | nil
  organizationCountry1?: string | nil
  organizationCommonName?: string | nil
  organizationgrade?: 
    type: array
  organizationGradeLevel?: string | nil
  organizationWebsite?: string | nil
  organizationtype?: string | nil

  