#%RAML 1.0 DataType

#This file is located at dataTypes/SFDCResponse-data-type.raml
   
type: object
properties:
  Response:
    type: array
    items: 
      properties:
        gsCRMGlobalID: string
        firstName: string
        lastName: string
        contactType: string
        sfdcStatus: statusResponse