#%RAML 1.0
title: gsusa-registration-api-s
version: v1.0
description: This System API will call the create/Update Person/Business Account in Salesforce along with Hybris System.

traits: 
  client-id-required:
      headers:
        client_id:
          type: string
        client_secret:
          type: string

types:
  SFDCaccount:     !include dataTypes/SFDCAccount-data-type.raml
  SAPaccount:      !include dataTypes/SAPHybrisAccount-data-type.raml
  errorResponse:   !include dataTypes/ErrorResponse-data-type.raml
  successResponse: !include dataTypes/SuccessResponse-data-type.raml
  statusResponse:  !include dataTypes/StatusResponse-data-type.raml
  sapResponse:     !include dataTypes/SAPResponse-data-type.raml
  sfdcResponse:    !include dataTypes/SFDCResponse-data-type.raml

           
/sfdc/v1/accounts:
         displayName: Operations Related to Account in Salesforce
         description: "Operations Related to Account in Salesforce"
         
         /createupdate:
          displayName: Accounts Creation/Updation in Salesforce System
          description: |
                 Working with accounts:
                  * Creating accounts
          post:
              is: [client-id-required]
              description: |
                  Create a New Account and Update Account in Salesforce
              body:
               application/json:
                 type: SFDCaccount
                 example: !include examples/post-sfdcaccounts-request-example.json
              responses:
                200:
                  description: Success Ok
                  body:
                    application/json:
                      type: sfdcResponse
                      example: !include examples/sfdcoutput-response-example.json
                201:
                  description: Created
                  body: 
                    application/json:
                      type: sfdcResponse
                      example: !include examples/sfdcoutput-response-example.json
                400:
                  description: Bad Request
                  body:
                    application/json:
                      type: sfdcResponse
                      example: !include examples/sfdcoutput-response-example.json
                401:
                  description: Unauthorized Access
                  body:
                    application/json:
                      type: sfdcResponse
                      example: !include examples/sfdcoutput-response-example.json       
                404:
                  description: Resource Not Found
                  body:
                    application/json:
                      type: sfdcResponse
                      example: !include examples/sfdcoutput-response-example.json   
                
/sap/v1/accounts:
     displayName: Operations Related to Account in SAP Hybris System
     description: "Operations Related to Account in SAP Hybris System"

     /createupdate:
        displayName: Accounts Creation and Updation in SAP Hybris System
        description: |
                 Working with accounts:
                  * Creating accounts in SAP Hybris
        post:
          is: [client-id-required]
          description: |
             Create a New Account and Update Account in SAP Hybris System
          body:
               application/json:
                 type: SAPaccount
                 example: !include examples/post-sapaccounts-request-example.json
          responses:
              200:
                description: Success Ok
                body:
                  application/json:
                    type: sapResponse
                    example: !include examples/sapoutput-response-example.json
              201:
                description: Created
                body: 
                  application/json:
                    type: sapResponse
                    example: !include examples/sapoutput-response-example.json
              400:
                description: Bad Request
                body:
                  application/json:
                    type: sapResponse
                    example: !include examples/sapoutput-response-example.json
              401:
                description: Unauthorized Access
                body:
                  application/json:
                    type: sapResponse
                    example: !include examples/sapoutput-response-example.json         
              404:
                description: Resource Not Found
                body:
                  application/json:
                    type: sapResponse
                    example: !include examples/sapoutput-response-example.json        