#%RAML 1.0 DataType

#This file is located at dataTypes/schoolRequest.raml

type: object
properties:
  id: string 
  schoolAccountName?: string | nil
  schoolPhone?: string | nil
  isOrganizationActive?: string 
  isSchoolActive?: string | nil
  schoolBillingCity?: string | nil
  schoolBillingState?: string | nil
  schoolBillingPostalCode?: string | nil
  schoolBillingCountry?: string | nil
  schoolBillingCountry1?: string | nil
  schoolCommonName?: string | nil
  schoolgrade?: 
    type: array
  schoolGradeLevel?: string | nil
  schoolWebsite?: string | nil

  