#%RAML 1.0 DataType

type: object
properties:
  LineNumber?: string | nil
  LineHybrisId?: string | nil
  Status?: string | nil
  Price?: number | nil
  OrderedFor?: string | nil
  Council?: string | nil
  LastPaymentDate?: string | nil
  ProductId?: string | nil
  Troops?: array | nil
  