#%RAML 1.0 DataType

type: object
properties:
  netSuiteItem?: string | nil
  netSuiteGLLocation?: string | nil
  startDate?: string | nil
  endDate?: string | nil
  membershipType?: string | nil
  councilId?: string | nil
  duration?: string | nil
  serviceUnit?: string | nil
  ActivityType?: string | nil
  requiredAge?: string | nil
  requiredGradeType?: string | nil
  physicalLocation?: string | nil
  sessionID?: string | nil
  code?: string | nil